version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ego-ai-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ego-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hello-world"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: ego-ai-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ego-ai-network

networks:
  ego-ai-network:
    driver: bridge
