services:
  db:
    image: postgres:16
    container_name: ego-ai-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ego-ai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ego-ai-pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ego-ai-network

  backend:
    build: ./backend
    container_name: ego-ai-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    networks:
      - ego-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: ego-ai-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ego-ai-network

volumes:
  postgres_data:

networks:
  ego-ai-network:
    driver: bridge