"""описание изменений

Revision ID: a6482e1be0e3
Revises: df7e9d27ea9d
Create Date: 2025-07-08 20:35:48.318919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6482e1be0e3'
down_revision: Union[str, None] = 'df7e9d27ea9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('events', sa.Column('type', sa.String(), nullable=False))
    op.drop_index('ix_events_google_event_id', table_name='events')
    op.drop_column('events', 'google_event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('google_event_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_events_google_event_id', 'events', ['google_event_id'], unique=False)
    op.drop_column('events', 'type')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###