deploy:
  needs: build-and-test
  if: github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to Remote Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/Ego_AI

          echo "Updating code..."
          git pull origin main

          echo "Updating .env variables (root)"
          update_env_var() {
            VAR_NAME="$1"
            VAR_VALUE="$2"
            if grep -q "^$VAR_NAME=" .env; then
              sed -i "s|^$VAR_NAME=.*|$VAR_NAME=$VAR_VALUE|" .env
            else
              echo "$VAR_NAME=$VAR_VALUE" >> .env
            fi
          }

          update_env_var POSTGRES_USER "${{ secrets.DB_USER }}"
          update_env_var POSTGRES_PASSWORD "${{ secrets.DB_PASSWORD }}"
          update_env_var POSTGRES_DB "${{ secrets.DB_NAME }}"

          echo "Updating backend/.env variables"
          mkdir -p backend
          if grep -q "^DATABASE_URL=" backend/.env; then
            sed -i "s|^DATABASE_URL=.*|DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@db:5432/${{ secrets.DB_NAME }}|" backend/.env
          else
            echo "DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@db:5432/${{ secrets.DB_NAME }}" >> backend/.env
          fi

          echo "Restarting services..."
          docker-compose down
          docker-compose up -d --build
